### PR TITLE
Migration to Jetpack Compose

### PR DESCRIPTION
**Pull request by its-me-debk007**
Solves #2 

There's just a small issue, that the image stored in the device doesn't show anything

### CODE REVIEW

**Comment by its-me-debk007** [comment]
I've fixed the bug related to image not saving properly

**Comment by raghavtilak** [comment]
Works Perfectly Fine 💯 
Thanks for your contribution 😄👍🏻

**Comment by raghavtilak** [comment]
hey @its-me-debk007 , there's one issue i found with your commit. 

https://github.com/raghavtilak/Paint/assets/74963954/f916f8f6-dc58-4f3b-840b-3d85b2d910a7

I think the bound should be set correctly, both above and below, user shouldn't be allowed to draw beyond the bounds.
or else we can allow the user to use the entire screen as a canvas and, the toolbar can be toggled, the toolbar should be above the canvas.

**Comment by its-me-debk007** [comment]
Oh!
Unfortunately I have my college exams going on. After the exams are over, I'll get back to it!

**Comment by raghavtilak** [comment]
> Oh! Unfortunately I have my college exams going on. After the exams are over, I'll get back to it!

Oh ok. No issues, I understand. Do as when you get time. 
All the best for your exams. 😄

**Pull request merged**
